apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: {{ .Values.grafana.datasources.prometheus.name }}
      type: {{ .Values.grafana.datasources.prometheus.type }}
      access: {{ .Values.grafana.datasources.prometheus.access }}
      url: {{ .Values.grafana.datasources.prometheus.url }}
      isDefault: {{ .Values.grafana.datasources.prometheus.isDefault }}
      editable: true
