apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
  - port: {{ .Values.grafana.service.port }}
    targetPort: http
    protocol: TCP
    name: http
{{- if eq .Values.grafana.service.type "NodePort" }}
    nodePort: {{ .Values.grafana.service.nodePort }}
{{- end }}
  selector:
    app: grafana
