apiVersion: v1
kind: Service
metadata:
  name: sipeed-prometheus
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.prometheus.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: prometheus
