apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
      evaluation_interval: 15s
      external_labels:
        cluster: 'sipeed-cm5'

    scrape_configs:
{{- range .Values.prometheus.scrapeConfigs }}
      - job_name: {{ .job_name | quote }}
{{- if .kubernetes_sd_configs }}
        kubernetes_sd_configs:
{{- toYaml .kubernetes_sd_configs | nindent 10 }}
{{- end }}
{{- if .relabel_configs }}
        relabel_configs:
{{- toYaml .relabel_configs | nindent 10 }}
{{- end }}
{{- if .static_configs }}
        static_configs:
{{- toYaml .static_configs | nindent 10 }}
{{- end }}
{{- end }}
