apiVersion: v1
kind: Service
metadata:
  name: sipeed-fan-controller
  labels:
    app.kubernetes.io/name: sipeed-fan-controller
    helm.sh/chart: sipeed-cm5-fancontrol
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: status
      protocol: TCP
      name: status
  selector:
    app.kubernetes.io/name: sipeed-fan-controller
