apiVersion: v1
kind: ServiceAccount
metadata:
  name: sipeed-fan-controller
  labels:
    app.kubernetes.io/name: sipeed-fan-controller
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
