apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sipeed-fan-controller
  labels:
    app.kubernetes.io/name: sipeed-fan-controller
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
