apiVersion: v1
kind: Service
metadata:
  name: sipeed-temp-exporter
  labels:
    app.kubernetes.io/name: sipeed-temp-exporter
    helm.sh/chart: sipeed-cm5-fancontrol
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.exporter.service.port }}
      targetPort: {{ .Values.exporter.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: sipeed-temp-exporter