# Default values for sipeed-cm5-fancontrol
# This is a YAML-formatted file.

controller:
  image:
    repository: ghcr.io/mi-q/sipeed-cm5-fancontrol
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  args:
    - --remote-method=http
    - --k8s-discovery  # Enable automatic discovery of temp exporter pods
    - --status-port=2506
    - --status-bind=0.0.0.0
  service:
    port: 2506
  securityContext:
    privileged: true
  
  # Fan controller configuration (loaded from ConfigMap)
  config:
    mode: auto  # "auto" or "manual"
    manualSpeed: 50  # 0-100, used when mode=manual
    tempLow: 30  # Celsius, low temp threshold
    tempHigh: 70  # Celsius, high temp threshold
    fanSpeedLow: 0  # 0-100, fan speed at tempLow
    fanSpeedHigh: 100  # 0-100, fan speed at tempHigh
    fanMinOperatingSpeed: 10  # Minimum % for fan to spin
    fanStopTemp: 20  # Below this temp, fan stops completely
    fanCurve: exponential  # "linear", "exponential", or "step"
    stepZones: "35:0,45:30,55:60,65:100"  # For step curve mode
    stepHysteresis: 2  # Degrees C for step mode hysteresis

exporter:
  image:
    repository: ghcr.io/mi-q/sipeed-temp-exporter
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  args:
    - --bind=0.0.0.0
    - --port=2505
  service:
    port: 2505